apiVersion: apps/v1
kind: Deployment
metadata:
  name: social-links
  namespace: social-links
  labels:
    app: social-links
spec:
  replicas: 2
  selector:
    matchLabels:
      app: social-links
  template:
    metadata:
      labels:
        app: social-links
    spec:
      containers:
        - name: nginx
          image: social-links-image
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10